# Generated by Django 3.0.5 on 2020-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=15)),
                ('No_of_Copies', models.CharField(max_length=9)),
            ],
        ),
    ]
