# Generated by Django 3.0.5 on 2020-05-07 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200508_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lend',
            old_name='USN',
            new_name='USNn',
        ),
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 28, 55, 333928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 28, 55, 504644, tzinfo=utc)),
        ),
    ]
