# Generated by Django 3.0.5 on 2020-05-07 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200508_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lend',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 31, 7, 893202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 31, 8, 42632, tzinfo=utc)),
        ),
    ]
