# Generated by Django 3.0.5 on 2020-05-07 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200508_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lend',
            old_name='USNn',
            new_name='USN',
        ),
        migrations.RenameField(
            model_name='lend',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 43, 5, 762634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 19, 43, 5, 812501, tzinfo=utc)),
        ),
    ]
