# Generated by Django 3.0.5 on 2020-05-07 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200508_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 21, 15, 12, 780431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='USN',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='lend',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 21, 15, 12, 831296, tzinfo=utc)),
        ),
    ]
