# Generated by Django 3.0.5 on 2020-05-08 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200508_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 14, 47, 37, 698689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 5, 23)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 14, 47, 37, 821363, tzinfo=utc)),
        ),
    ]
