# Generated by Django 3.0.5 on 2020-05-10 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0029_auto_20200509_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 10, 3, 23, 784657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 5, 25)),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 10, 3, 23, 873989, tzinfo=utc)),
        ),
    ]
