# Generated by Django 3.0.5 on 2020-05-10 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0030_auto_20200510_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 10, 11, 10, 990285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 10, 11, 10, 991198, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='lends',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                (
                'issue_date', models.DateField(default=datetime.datetime(2020, 5, 10, 10, 11, 10, 856003, tzinfo=utc))),
                ('due_date', models.DateField(default=datetime.date(2020, 5, 25))),
                ('USN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.books')),
            ],
        ),
    ]
