# Generated by Django 3.0.5 on 2020-05-11 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0032_auto_20200512_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 19, 55, 39, 349572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 19, 55, 39, 349572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lends',
            name='USN',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='lends',
            name='book_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='lends',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 19, 55, 39, 301705, tzinfo=utc)),
        ),
    ]
