# Generated by Django 3.0.5 on 2020-05-11 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0033_auto_20200512_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 21, 6, 723326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 21, 6, 725327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lends',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 21, 6, 513295, tzinfo=utc)),
        ),
    ]
