# Generated by Django 3.0.5 on 2020-05-11 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0034_auto_20200512_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lends',
            name='due_date',
        ),
        migrations.AddField(
            model_name='lends',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 49, 8, 29272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='books',
            name='last_borrowed',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 49, 8, 118738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 49, 8, 119786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lends',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 20, 49, 8, 29272, tzinfo=utc)),
        ),
    ]
